# Generated by Django 2.2.12 on 2020-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_r_no', models.CharField(max_length=255)),
                ('l_r_date', models.DateField(blank=True, null=True)),
                ('bale_no', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('pcs_mtr', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('frieght', models.FloatField(blank=True, null=True)),
                ('transport', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery', models.DateField(blank=True, null=True)),
                ('reciept', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
