# Generated by Django 2.2.12 on 2020-06-06 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerdata',
            name='l_r_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='ledgerdata',
            unique_together={('user', 'l_r_no')},
        ),
    ]
