# Generated by Django 2.2.12 on 2020-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerdata',
            name='bill_ammount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ledgerdata',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgerdata',
            name='l_r_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ledgerdata',
            name='frieght',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ledgerdata',
            name='pcs_mtr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ledgerdata',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
