# Generated by Django 3.0.5 on 2020-04-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerdata',
            name='reciept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerdata',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
