# Generated by Django 5.2.1 on 2025-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20200618_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerdata',
            name='l_r_no',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
