# Generated by Django 2.2.12 on 2020-05-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20200531_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerdata',
            old_name='l_r_count',
            new_name='no_of_bale',
        ),
    ]
