# Generated by Django 2.2.12 on 2020-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20200531_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerdata',
            name='l_r_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
