# Generated by Django 2.2.12 on 2020-06-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20200602_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerdata',
            options={'ordering': ['l_r_date']},
        ),
    ]
