# Generated by Django 2.2.12 on 2020-06-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20200602_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerdata',
            options={'ordering': ['l_r_date', 'id']},
        ),
    ]
