# Generated by Django 5.2.1 on 2025-10-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('physical', 'Physical'), ('agent', 'Agent')], default='phone', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
