# Generated by Django 5.2.1 on 2025-10-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderlist', '0002_order_agent_name_order_mode_order_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='bill_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent_name',
            field=models.CharField(blank=True, help_text="Required only when mode is 'Agent'", max_length=255, null=True),
        ),
    ]
