# Generated by Django 3.0.5 on 2020-07-04 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatelistData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('hsn', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('company', 'item')},
            },
        ),
        migrations.CreateModel(
            name='RatelistDataHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_price', models.FloatField()),
                ('p_date', models.DateField()),
                ('s_price', models.FloatField()),
                ('s_date', models.DateField()),
                ('ratelistdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='ratelist.RatelistData')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
