# Generated by Django 3.0.5 on 2020-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('hsn', models.CharField(max_length=255)),
                ('pcs_mtr', models.FloatField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
